services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: testing
    command: uvicorn src.application:application --host=0.0.0.0 --reload
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src/
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17.4
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRESQL__USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL__PASSWORD}
      - POSTGRES_DB=${POSTGRESQL__DATABASE}
    ports:
      - "${POSTGRESQL__PORT}:${POSTGRESQL__PORT}"
    volumes:
      - devdb-volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

name: uow
volumes:
  devdb-volume: